# Generated by Django 5.0.1 on 2024-04-24 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farmhive", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalFarms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_name", models.CharField(max_length=150)),
                ("title", models.CharField(default="Farm Hive", max_length=255)),
                ("description", models.CharField(max_length=500)),
                ("total_departments", models.IntegerField(blank=True, default=0)),
                ("upload_video", models.FileField(upload_to="digifarms_images")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farmhive.departments",
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="AboutContent",
            new_name="AboutFarmHive",
        ),
        migrations.DeleteModel(
            name="AboutTheDepartment",
        ),
        migrations.DeleteModel(
            name="DigitalFarmsEvents",
        ),
    ]
