# Generated by Django 5.0.1 on 2024-04-26 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, unique=True)),
                ("image", models.ImageField(upload_to="about_images")),
                ("content", models.TextField(max_length=2000, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChangeHeaderImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("select_image", models.ImageField(upload_to="header_images")),
                ("short_description", models.CharField(blank=True, max_length=150)),
                (
                    "short_content",
                    models.CharField(default="Tech Farm Hub", max_length=200),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChangeProjectHeaderImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Project Name", max_length=20)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="project_header_image"),
                ),
                ("short_content", models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.IntegerField()),
                ("email_address", models.EmailField(max_length=254)),
                ("location", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FooterArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("update_contact", models.CharField(max_length=15, unique=True)),
                ("address", models.TextField()),
                ("work_hours", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("image_file", models.ImageField(unique=True, upload_to="gallery")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="news_article_images")),
                ("content", models.TextField()),
                ("full_content", models.TextField()),
                ("date_published", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Partners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("logo", models.ImageField(upload_to="partners_image")),
                ("content", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("descirption", models.CharField(max_length=100)),
                ("videofile", models.FileField(default="", upload_to="project_video")),
                (
                    "country",
                    models.CharField(default="Ghana, Koforidua", max_length=100),
                ),
                ("content", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_of_service", models.CharField(max_length=100, unique=True)),
                ("content", models.CharField(max_length=255, unique=True)),
                ("full_content", models.TextField(max_length=2000, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SocialMediaLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facebook", models.URLField(blank=True, null=True)),
                ("twitter", models.URLField(blank=True, null=True)),
                ("linkedIn", models.URLField(blank=True, null=True)),
                ("google", models.URLField(blank=True, null=True)),
                ("instagram", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[("mrs", "Mrs"), ("mr", "Mr"), ("ms", "Ms")],
                        max_length=10,
                    ),
                ),
                ("name_of_team_member", models.CharField(max_length=100, unique=True)),
                ("position", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="team_member_images")),
                ("bio", models.TextField()),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_of_course", models.CharField(max_length=150, unique=True)),
                (
                    "videofile",
                    models.FileField(unique=True, upload_to="tech_hive_videos"),
                ),
                ("description", models.CharField(max_length=255, unique=True)),
                ("cate_created", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FarmHive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("videofile", models.FileField(unique=True, upload_to="farm_hive")),
                ("description", models.CharField(max_length=255)),
                ("_date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "departments",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MultimediaHive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("videofile", models.FileField(unique=True, upload_to="farm_hive")),
                ("description", models.CharField(max_length=255)),
                ("_date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "departments",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.department",
                    ),
                ),
            ],
        ),
    ]
