# Generated by Django 5.0.1 on 2024-04-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChangeHeaderImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("select_image", models.ImageField(upload_to="header_images")),
                ("short_description", models.CharField(blank=True, max_length=150)),
                (
                    "short_content",
                    models.CharField(default="Tech Farm Hub", max_length=200),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.IntegerField()),
                ("email_address", models.EmailField(max_length=254)),
                ("location", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="FooterArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("update_contact", models.CharField(max_length=15, unique=True)),
                ("address", models.TextField()),
                ("work_hours", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="HomeLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                ("contact", models.CharField(max_length=15)),
                ("facebook_loink", models.URLField()),
                ("x_link", models.URLField()),
                ("linked_in_link", models.URLField()),
                ("google_link", models.URLField()),
                ("instagram_link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="news_article_images")),
                ("content", models.TextField()),
                ("full_content", models.TextField()),
                ("date_published", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Partners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("image", models.ImageField(upload_to="partners_image")),
                ("short_content", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("descirption", models.CharField(max_length=100)),
                (
                    "country",
                    models.CharField(default="Ghana, Koforidua", max_length=100),
                ),
                ("content", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[("mr", "Mr"), ("mrs", "Mrs"), ("ms", "Ms")],
                        max_length=10,
                    ),
                ),
                ("name_of_team_member", models.CharField(max_length=100, unique=True)),
                ("positon", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="team_member_images")),
                (
                    "short_content",
                    models.CharField(
                        blank=True, default="Tech Farm Hub", max_length=255
                    ),
                ),
                ("full_content", models.TextField()),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
