# Generated by Django 5.0.1 on 2024-04-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="title",
            field=models.CharField(
                choices=[("mrs", "Mrs"), ("mr", "Mr"), ("ms", "Ms")], max_length=10
            ),
        ),
    ]
