# Generated by Django 5.0.1 on 2024-04-26 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Locations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=255, unique=True)),
                ("country_flag", models.ImageField(upload_to="country_flags")),
                ("city", models.CharField(max_length=255, unique=True)),
                ("date_created", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name="Courses",
            new_name="Section",
        ),
        migrations.RenameField(
            model_name="multimediahive",
            old_name="_date_created",
            new_name="date_created",
        ),
        migrations.AlterField(
            model_name="team",
            name="title",
            field=models.CharField(
                choices=[("mr", "Mr"), ("mrs", "Mrs"), ("ms", "Ms")], max_length=10
            ),
        ),
        migrations.CreateModel(
            name="Prices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=6)),
                ("currency", models.CharField(max_length=3)),
                ("date_created", models.DateField(auto_now_add=True)),
                (
                    "farm_hive_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.farmhive"
                    ),
                ),
                (
                    "multimedia_hive_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.multimediahive",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Promotions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_promotion_active", models.BooleanField(default=False)),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "get_amount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.prices"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TechHive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("videofile", models.FileField(unique=True, upload_to="farm_hive")),
                ("description", models.CharField(max_length=255)),
                ("_date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "departments",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.department",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="prices",
            name="tech_hive_price",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.techhive"
            ),
        ),
    ]
