# Generated by Django 5.0.1 on 2024-04-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_team_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, unique=True)),
                ("image", models.ImageField(upload_to="about_images")),
                ("content", models.TextField(max_length=2000, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_of_service", models.CharField(max_length=100, unique=True)),
                ("content", models.CharField(max_length=255, unique=True)),
                ("full_content", models.TextField(max_length=2000, unique=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
