# Generated by Django 5.0.1 on 2024-04-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_locations_rename_courses_section_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultimediahiveGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("image_file", models.ImageField(unique=True, upload_to="gallery")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TechhiveGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("image_file", models.ImageField(unique=True, upload_to="gallery")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name="Gallery",
            new_name="FarmhiveGallery",
        ),
        migrations.RenameField(
            model_name="changeheaderimages",
            old_name="short_content",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="changeheaderimages",
            old_name="short_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="changeheaderimages",
            old_name="select_image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="farmhive",
            old_name="_date_created",
            new_name="date_created",
        ),
        migrations.RenameField(
            model_name="techhive",
            old_name="_date_created",
            new_name="date_created",
        ),
        migrations.AlterField(
            model_name="team",
            name="title",
            field=models.CharField(
                choices=[("ms", "Ms"), ("mrs", "Mrs"), ("mr", "Mr")], max_length=10
            ),
        ),
    ]
