# Generated by Django 5.0.1 on 2024-04-25 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_about_services"),
    ]

    operations = [
        migrations.CreateModel(
            name="Techhive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="projects",
            name="videofile",
            field=models.FileField(default="", upload_to="project_video"),
        ),
        migrations.AlterField(
            model_name="team",
            name="title",
            field=models.CharField(
                choices=[("ms", "Ms"), ("mrs", "Mrs"), ("mr", "Mr")], max_length=10
            ),
        ),
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_of_course", models.CharField(max_length=150, unique=True)),
                (
                    "videofile",
                    models.FileField(unique=True, upload_to="tech_hive_videos"),
                ),
                ("description", models.CharField(max_length=255, unique=True)),
                ("cate_created", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.techhive"
                    ),
                ),
            ],
        ),
    ]
