# Generated by Django 5.0.1 on 2024-04-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_rename_positon_team_position_alter_team_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeProjectHeaderImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="project_header_image"),
                ),
                ("short_content", models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name="team",
            name="title",
            field=models.CharField(
                choices=[("ms", "Ms"), ("mrs", "Mrs"), ("mr", "Mr")], max_length=10
            ),
        ),
    ]
