# Generated by Django 5.0.1 on 2024-04-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_changeprojectheaderimage_alter_team_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="changeprojectheaderimage",
            name="name",
            field=models.CharField(default="Project Name", max_length=20),
        ),
        migrations.AlterField(
            model_name="changeprojectheaderimage",
            name="short_content",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="team",
            name="title",
            field=models.CharField(
                choices=[("ms", "Ms"), ("mr", "Mr"), ("mrs", "Mrs")], max_length=10
            ),
        ),
    ]
