# Generated by Django 5.0.1 on 2024-04-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_socialmedialinks_delete_homelinks_alter_team_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("image_file", models.ImageField(unique=True, upload_to="gallery")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name="team",
            old_name="full_content",
            new_name="bio",
        ),
        migrations.RemoveField(
            model_name="team",
            name="short_content",
        ),
        migrations.AlterField(
            model_name="team",
            name="title",
            field=models.CharField(
                choices=[("mrs", "Mrs"), ("mr", "Mr"), ("ms", "Ms")], max_length=10
            ),
        ),
    ]
