# Generated by Django 5.0.1 on 2024-04-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_gallery_rename_full_content_team_bio_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="partners",
            old_name="short_content",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="partners",
            old_name="image",
            new_name="logo",
        ),
        migrations.AlterField(
            model_name="team",
            name="title",
            field=models.CharField(
                choices=[("ms", "Ms"), ("mr", "Mr"), ("mrs", "Mrs")], max_length=10
            ),
        ),
    ]
